spring.application.name=mb-mini

# New Redis DB for testing
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=5

spring.jmx.enabled=false

# New MySQL DB for testing
spring.datasource.url=jdbc:mysql://localhost:3306/test_new
spring.datasource.username=dakshjain
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop