spring.application.name=mb-mini
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=4
spring.jmx.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/mb_mini_cart
spring.datasource.username=dakshjain
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.security.enabled=false

server.port=8080
spring.main.allow-bean-definition-overriding=true

spring.kafka.topic.name=basketDeplete


cart.service.url=http://localhost:8082
cart.item.update.url=http://localhost:8082/cart/processQuantityUpdate


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=catalog-group