spring.application.name=mb-mini
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=4
spring.jmx.enabled=false
spring.data.redis.timeout=295200

spring.datasource.url=jdbc:mysql://localhost:3306/mb_mini_cart
spring.datasource.username=dakshjain
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.security.enabled=false
local.server.port=8081
test.server.port=8081
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

spring.main.allow-bean-definition-overriding=true

opc.api.key=562179c19e0f4fc39c553140c605abbb
opc.api.url=https://api.opencagedata.com/geocode/v1/json

ors.api.url=https://api.openrouteservice.org
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImExZmE1YmY0ZGJkMTQ0Y2JiNGIxNzcxZTBjNmE3OTgwIiwiaCI6Im11cm11cjY0In0=

pin.api.url=https://api.postalpincode.in/pincode
